{% set data = load_setup_py_data() %}

package:
  name: wsp-cheval
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: python setup.py --quiet install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
  run:
    - python >=3.6
    - pandas >=0.22,<1.5
    - numpy >=1.15
    - numba >=0.45
    - numexpr >=2.6
    - astor >=0.7.1
    - attrs >=19.3
    - deprecated >=1.2.6

about:
  home: https://github.com/wsp-sag/cheval
  license: MIT
  license_file: LICENSE
  summary: A Python package for high-performance discrete-choice (logit) model evaluation in travel demand modelling

extra:
  maintainers:
    - Peter Kucirek
    - Brian Cheung
    - Andrew Clarry
