{% set data = load_setup_py_data() %}

package:
  name: wsp-cheval
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: python setup.py --quiet install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
  run:
    - python >=3.7
    - pandas >=0.24,<1.5
    - numpy >=1.20
    - numba >=0.48
    - numexpr
    - astor
    - attrs >=19.3

about:
  home: https://github.com/wsp-sag/cheval
  license: MIT
  license_file: LICENSE
  summary: A Python package for high-performance discrete-choice (logit) model evaluation in travel demand modelling

extra:
  maintainers:
    - Peter Kucirek
    - Brian Cheung
    - Andrew Clarry
